#!/bin/bash

spark-submit \
--master yarn \
--name "WarnStatistics-$1" \
--repositories https://maven.aliyun.com/repository/public, \
--packages org.apache.spark:spark-streaming-kafka-0-10_2.12:3.4.1,org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1,com.mysql:mysql-connector-j:8.0.33 \
--deploy-mode cluster \
--driver-memory 4g \
--driver-cores 1 \
--num-executors 2 \
--executor-memory 2g \
--executor-cores 1 \
hdfs://hadoop-master-146/structured-streaming/jobs/warn-statistics.jar \
-Dio.netty.tryReflectionSetAccessible=true \
2>&1 &
